In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import rcParams
from matplotlib.cm import rainbow
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [49]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics

In [3]:
df = pd.read_csv('dataset.csv')
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [4]:
types = {'positive':0,'negative':0}
for i in range(len(df)):
    if df['target'][i]==0:
        types['negative']+=1
    else:
        types['positive']+=1
types

{'positive': 165, 'negative': 138}

In [55]:
x = df[['cp','restecg','thalach','slope']]
y = df.target

In [92]:
xtrain,xtest,ytrain,ytest = train_test_split(x, y, test_size = 0.2, shuffle = True)

In [101]:
lr = LogisticRegression().fit(xtrain,ytrain)
print("Accuracy Score ",metrics.accuracy_score(lr.predict(xtest),ytest))
print("F-score ",metrics.f1_score(lr.predict(xtest),ytest))

Accuracy Score  0.7540983606557377
F-score  0.7457627118644068


In [74]:
lr.predict_proba([xtest[0]])

array([[0.21461924, 0.78538076]])

In [72]:
xtest[0]

array([0.25      , 0.33333333, 0.        , 0.77099237, 1.        ])

In [94]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout
import tensorflow as tf
from tensorflow.keras.losses import categorical_crossentropy

In [87]:
model = Sequential()
model.add(tensorflow.keras.Input(shape=(4,)))
model.add(Dense(16,activation='relu'))
model.add(Dense(4,activation='relu'))
model.add(Dense(1,activation='sigmoid'))
print(model.summary())

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_3 (Dense)              (None, 16)                80        
_________________________________________________________________
dense_4 (Dense)              (None, 4)                 68        
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 5         
Total params: 153
Trainable params: 153
Non-trainable params: 0
_________________________________________________________________
None


In [97]:
model.compile('rmsprop',categorical_crossentropy,['accuracy'])

In [98]:
model.fit(xtrain,ytrain,epochs = 10,batch_size=16, validation_data=(xtest,ytest))

Epoch 1/10
16/16 [==============================] - 0s 6ms/step - loss: 6.6994e-08 - accuracy: 0.5620 - val_loss: 5.6673e-08 - val_accuracy: 0.4754
Epoch 2/10
16/16 [==============================] - 0s 2ms/step - loss: 6.6994e-08 - accuracy: 0.5620 - val_loss: 5.6673e-08 - val_accuracy: 0.4754
Epoch 3/10
16/16 [==============================] - 0s 2ms/step - loss: 6.6994e-08 - accuracy: 0.5620 - val_loss: 5.6673e-08 - val_accuracy: 0.4754
Epoch 4/10
16/16 [==============================] - 0s 2ms/step - loss: 6.6994e-08 - accuracy: 0.5620 - val_loss: 5.6673e-08 - val_accuracy: 0.4754
Epoch 5/10
16/16 [==============================] - 0s 2ms/step - loss: 6.6994e-08 - accuracy: 0.5620 - val_loss: 5.6673e-08 - val_accuracy: 0.4754
Epoch 6/10
16/16 [==============================] - 0s 2ms/step - loss: 6.6994e-08 - accuracy: 0.5620 - val_loss: 5.6673e-08 - val_accuracy: 0.4754
Epoch 7/10
16/16 [==============================] - 0s 2ms/step - loss: 6.6994e-08 - accuracy: 0.5620 - val_loss

In [90]:
#-------------------------------------------------------------------------------------------------------


array([0.60416667, 0.        , 0.5       , 0.25954198, 0.5       ])

In [19]:
df.corr()['target']

age        -0.225439
sex        -0.280937
cp          0.433798
trestbps   -0.144931
chol       -0.085239
fbs        -0.028046
restecg     0.137230
thalach     0.421741
exang      -0.436757
oldpeak    -0.430696
slope       0.345877
ca         -0.391724
thal       -0.344029
target      1.000000
Name: target, dtype: float64

In [17]:
y.value_counts()

1    165
0    138
Name: target, dtype: int64

In [43]:
x = df[['cp','restecg','thalach','slope']]

In [44]:
x

cp  restecg  thalach  slope
0     3        0      150      0
1     2        1      187      0
2     1        0      172      2
3     1        1      178      2
4     0        1      163      2
..   ..      ...      ...    ...
298   0        1      123      1
299   3        1      132      1
300   0        1      141      1
301   0        1      115      1
302   1        0      174      1

[303 rows x 4 columns]

In [41]:
from sklearn.preprocessing import MinMaxScaler
x = MinMaxScaler().fit_transform(x)
#x = df[['cp','restecg','thalach','slope']]
y = df['target']
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,stratify = y, shuffle = True)

In [99]:
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
lr = LogisticRegression()
lr.fit(xtrain,ytrain)
predictions = lr.predict(xtest)
from sklearn.metrics import accuracy_score,classification_report
print(accuracy_score(predictions,ytest))
print(classification_report(predictions,ytest))

0.7540983606557377
              precision    recall  f1-score   support

           0       0.75      0.77      0.76        31
           1       0.76      0.73      0.75        30

    accuracy                           0.75        61
   macro avg       0.75      0.75      0.75        61
weighted avg       0.75      0.75      0.75        61



In [23]:
result = str(lr.predict([[1,2,3,1]]))
if result=='[1]':
    send_mail('[1]')
    print("sending mail")
else:
    send_mail('[0]')
    print("sending mail")

sending mail


In [9]:
import pickle
pickle_out = open("classifier_heart.pkl","wb")
pickle.dump(lr,pickle_out)
pickle_out.close()

In [10]:
import smtplib, ssl